resolver: lts-10.3
packages:
- '.'
- '../../libs/types-common'
- location:
    git: https://github.com/kim/hs-collectd
    commit: '0.0.0.2'
  extra-dep: true

flags:
  types-common:
    cql: False
    protobuf: True
    arbitrary: True

extra-deps:
- aeson-1.1.0.0
- snappy-0.2.0.2
- snappy-framing-0.1.0
- swagger-0.3.0

allow-newer: true
