resolver: lts-10.3
packages:
- '.'
- '../../libs/types-common'
- location:
    git: https://github.com/kim/hs-collectd
    commit: '0.0.0.2'
  extra-dep: true
- location:
    git: https://github.com/kim/snappy-framing
    commit: d99f702c0086729efd6848dea8a01e5266c3a61c
  extra-dep: true

flags:
  types-common:
    cql: False
    protobuf: True
    arbitrary: True

extra-deps:
- snappy-0.2.0.2
