flags: {}
extra-package-dbs: []
packages:
- .
- ../../libs/cargohold-types
- ../../libs/types-common
- ../../libs/ropes
- ../../libs/wai-utilities
- ../../libs/bilge
- ../../libs/metrics-core
- ../../libs/metrics-wai
resolver: lts-10.3
extra-deps:
- mime-0.4.0.2
flags:
  types-common:
    arbitrary: True
    protobuf: True
