resolver: lts-10.3
packages:
- '.'
- '../../libs/bilge'
- '../../libs/types-common'
- '../../libs/wai-utilities'
- '../../libs/metrics-core'
- '../../libs/metrics-wai'

flags:
  types-common:
    protobuf: True
    arbitrary: True

extra-deps: []
extra-package-dbs: []
