resolver: lts-10.3
packages:
- '.'
- '../../libs/api-bot'
- '../../libs/api-client'
- '../../libs/bilge'
- '../../libs/brig-types'
- '../../libs/cargohold-types'
- '../../libs/galley-types'
- '../../libs/gundeck-types'
- '../../libs/metrics-core'
- '../../libs/types-common'
- location:
    git: https://github.com/wireapp/cryptobox-haskell
    commit: 7546a1a25635ef65183e3d44c1052285e8401608
  extra-dep: true

extra-deps:
- currency-codes-2.0.0.0
- mime-0.4.0.2
flags:
  types-common:
    protobuf: True
    arbitrary: True
